### ISSUE TITLE
Incomplete README

### ISSUE THREAD

**Issue by jonlavoie** [fab1an-q/Pyrpl-F#1]
I don't think there is enough information in the README to get started. Need some basic getting started instructions.

**Comment by fab1an-q** [comment]
Shouldn't have invited jonlavoie to the repo! ;)
Ok, but let me add a few functionalities to the code before, so I can fill the readme with actually useful information.

**Comment by fab1an-q** [comment]
Updated the Readme file. Closing this issue.
